# Generated by Django 3.0.8 on 2020-09-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='StatusEng',
            new_name='statusEng',
        ),
    ]
