# Generated by Django 3.0.8 on 2020-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0003_auto_20200901_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='applicationNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='documentDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='documentNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='documentTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='documentTitleEng',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='registrationNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='statusEng',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='step',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='trialNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
